### ISSUE TITLE
Specification of dtype

### ISSUE THREAD

**Issue by rreusser** [mikolalysenko/zeros#1]
It would be nice if it were possible to pass a dtype to zeros. This would make it possible to say:

```
z = zeros( existingArray.shape, dtype='uint16' )
```

It seems like inclusion of typedarray-pool as a dependency would make this pretty straightforward, but it's more than necessary. All that's really needed is a function that translates the dtype string to a constructor.

In lieu of this (or if I'm missing the way to do this), is there a good way to construct an ndarray with the same shape and datatype as an existing array? I could leave construction of all work arrays to the user, but that's more than a little cumbersome.

**Comment by rreusser** [comment]
Note: I'm glad to submit a pull request; I just don't know how you'd prefer to handle this (or if it's already handled) in a way that fits into the ndarray universe.

**Comment by mikolalysenko** [comment]
I really want to deprecate this module and move it over to this:  https://www.npmjs.com/package/ndarray-scratch

But I would be ok with a PR, since from a usability stand point there are still some advantages here.

**Comment by rreusser** [comment]
(Also: Yeah, ndarray-scratch… knew I'd seen that but forgot it's what I was looking for. I'll probably just use that anyway.)

**Comment by rreusser** [comment]
Merged & published.
